/**
 * Embedded Config Module
 *
 * Provides access to embedded configuration and assets.
 * For embedded builds, returns bundled YAML and base64-encoded logos.
 * For generic builds, returns null (config loaded at runtime).
 *
 * The actual embedded data is generated by scripts/embed-config.ts
 * which overwrites src/config/embedded.generated.ts.
 */

import { embeddedYaml, embeddedLogos } from './embedded.generated';

/**
 * Embedded configuration data structure.
 */
export interface EmbeddedData {
  /** YAML config content (flat structure) */
  yaml: string;
  /** Logo filename to data URL mapping */
  logos: Record<string, string>;
}

/**
 * Get embedded configuration data.
 *
 * @returns Embedded YAML and logos, or null for generic builds
 */
export function getEmbeddedConfig(): EmbeddedData | null {
  if (!embeddedYaml) {
    return null;
  }
  return {
    yaml: embeddedYaml,
    logos: embeddedLogos,
  };
}

/**
 * Get embedded logos mapping.
 *
 * @returns Logo filename to data URL mapping, or null for generic builds
 */
export function getEmbeddedLogos(): Record<string, string> | null {
  if (!embeddedYaml) {
    return null;
  }
  return embeddedLogos;
}

/**
 * Check if running in embedded mode.
 *
 * @returns true if embedded config is available
 */
export function isEmbeddedBuild(): boolean {
  return embeddedYaml !== null;
}
